# Generated by Django 3.2.4 on 2022-10-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_dare',
            new_name='hire_date',
        ),
    ]
