# Generated by Django 3.2.16 on 2022-12-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_hire_dare_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
