# Generated by Django 3.2.16 on 2022-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
