# Generated by Django 3.2.16 on 2022-12-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_auto_20221204_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='photo/'),
        ),
    ]
