# Generated by Django 4.1.3 on 2022-12-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
