# Generated by Django 3.2.16 on 2023-01-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=0, max_length=50)),
                ('psd', models.CharField(max_length=100)),
            ],
        ),
    ]
